### ISSUE TITLE
Add a controllable level of randomization

### ISSUE THREAD

**Issue by ycollet** [x42/avldrums.lv2#26]
To add some kind of 'human feeling', is it possible to add some randomization of the time an element is played and also on the amplitude of the sound of the element ?

**Comment by x42** [comment]
This is outside the scope of the plugin for various reasons.

Fist and foremost: this is a host feature. Ideally the MIDI data itself is changed, so that every time you listen or export a song the result is identical and not random.

Also note that human players don't randomize. The super simple version:  play the snare a bit early and the kick a bit late. But micro-timing is a lot more complex https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127902

**Comment by ycollet** [comment]
Thanks for your answer.
I feared such an answer :) 
Most of DAW I use have not implemented this. So, I was wondering if it was possible to add this on the plugin side.
Nevertheless, thanks a lot for the link to the paper.
I close the ticket.
